updated incorrect description of input object.
Old
  // responses is an array of following structure:
  // {
  //   response: string;
  //   context?: string;
  // }

The error obtained in running the code : 
universal-sentence-encoder:17 Uncaught (in promise) TypeError: e.normalize is not a function
    at universal-sentence-encoder:17
    at c.encode (universal-sentence-encoder:17)
    at universal-sentence-encoder:17
    at Array.map (<anonymous>)
    at j.tokenizeStrings (universal-sentence-encoder:17)
    at universal-sentence-encoder:17
    at tfjs:17
    at e.t.scopedRun (tfjs:17)
    at e.t.tidy (tfjs:17)
    at Object.bx [as tidy] (tfjs:17)

This error is  due to incorrect object definition of "input"
On observation of  the code of universal-sentence-encoder , we see that  
---
embed(e) {
            const n = t.tidy(()=>{
                const t = this.tokenizeStrings(e.queries, f)
                  , n = this.tokenizeStrings(e.responses, f);
                if (null != e.contexts && e.contexts.length !== e.responses.length)
                    throw new Error("The length of response strings and context strings need to match.");
                const o = e.contexts || [];
---
So e.queries and e.contexts show that the input object should be

input =  
{
    queries: string[],
    responses: string[],
    contexts:string[]
}

So that i what i propose be updated in the readme